# Generated by Django 5.1.7 on 2025-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="название")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="описание"),
                ),
            ],
            options={
                "verbose_name": "машина",
                "verbose_name_plural": "машины",
            },
        ),
    ]
