# Generated by Django 5.1.7 on 2025-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_milage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milage',
            options={'ordering': ('milage', '-year'), 'verbose_name': 'пробег', 'verbose_name_plural': 'пробег'},
        ),
    ]
