# Generated by Django 5.1.7 on 2025-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_owner_alter_moto_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='цена'),
        ),
    ]
