# Generated by Django 5.1.7 on 2025-04-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_cars_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
